### ISSUE TITLE
Extra div added to item's RTE Field while editing

### ISSUE THREAD

**Issue by onpoc** [alan-null/sc_ext#106]
### Steps to Reproduce the Problem
  1. Go to any item's RTE (Rich Text Editor) Field and click on Show Editor.
  2. Now do any changes and save and come back to page item. 
  3. Now if you again click show editor on RTE then you will see some extra div will be added.
  4. The blow div has been added at the bottom of RTE markup:
     **<br />
         <div id="sc-ext-modal" class="launcher-modal">
              <div class="launcher-modal-content"><input id="sc-ext-searchBox" class="search-field" />
                 <ul id="sc-ext-searchResults" class="term-list hidden"></ul>
              </div>
         </div>**

### Expected Behavior 
...
These extra div should not be added.
### Actual Behavior
...
These extra div is going to raise the design issue on page after every change one block of these div are going to appended.

### Specifications
Sitecore version: 8.1 (revision 160302)

**Comment by alan-null** [comment]
Hi @onpoc 

Thank you for the report. I really appreciate it. 
Do you think that issue reported here: #75 is the same?

**Comment by onpoc** [comment]
Hi @alan-null,
Yes #75 is looks same as I replicate on my system with firefox extension.
So are we going to fix this issue or already fixed?

**Comment by alan-null** [comment]
@onpoc 
It's fixed but not released yet. 
I hope to release a new version by the end of the month. 
For now you can switch to chrome or disable Launcher module in settings as a workaround. 

I will close this one as a duplicate.
