### ISSUE TITLE
important Dialog boxes not shown in sitecore 7.2

### ISSUE THREAD

**Issue by 4Dinand2** [alan-null/sc_ext#111]
### Steps to Reproduce the Problem
  1. Sitecore 7.2 content editor
  1. pick any item
  1. menu -> Publish -> (ribbon) ->publish site or publish item.
  
### Expected Behavior 
... Open dialog with publish actions

### Actual Behavior
... dialogwill not turn up.

### Specifications
Sitecore version: 7.2 (revision 140526)
Firefox 57.0b11 (64-bit)
windows 10
Neither working: sitecore (Licenses, About)

Same functions works in chrome.

**Error reporting** : 
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: this.destination.parentElement.querySelectorAll(...)[1] is undefined
Stack trace:
ListField</ListField.prototype.initialize@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:4:6776
GoToDatasourceModule</GoToDatasourceModule.prototype.getFields@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:4:307
GoToDatasourceModule</GoToDatasourceModule.prototype.refreshFields@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:4:385
GoToDatasourceModule</GoToDatasourceModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:31815
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792
An error occured in the proxy function.
Application.js:2:20652
Please report it here: https://github.com/alan-null/sc_ext/issues/new
Application.js:2:20707
TypeError: section.onclick is null
Stack trace:
FieldInspectorModule</FieldInspectorModule.prototype.getSectionName@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:23433
_loop_3@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:17554
_loop_2@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19096
FieldInspectorModule</FieldInspectorModule.prototype.insertControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:19153
FieldInspectorModule</FieldInspectorModule.prototype.refreshControls@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16900
FieldInspectorModule</FieldInspectorModule.prototype.initialize/<@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:3:16157
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20999
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
HTMLHelpers</HTMLHelpers.addProxyToFunction/fn.prototype[functionName]@moz-extension://33d9a161-2d78-4457-a644-bed0645ef419/sc_ext/Application.js:2:20965
onclick@http://com.athlon.local/sitecore/shell/Applications/Content%20editor.aspx?sc_lang=en:1:19
Application.js:2:20792

**Comment by alan-null** [comment]
Hey @4Dinand2,

Are you using self hosted version:
https://alan-null.github.io/2017/09/sitecore-extensions-ff
or the one from ff-store?
https://addons.mozilla.org/pl/firefox/addon/sitecore-extensions/

You can also find your current version by clicking on extension/addon icon 
![image](https://user-images.githubusercontent.com/6848691/31999977-6ec7abae-b995-11e7-953b-d1f360f09618.png)

**Comment by 4Dinand2** [comment]
Hello Alan.
Sorry, my mistake.... this was for the sitecore community...
Yesterday I installed your extensions and used them on sc 8.2.
Perfect, thanks for the tool, it's helpfull and easy....( I used 4
functions at the time (database bar, change database, go to field, search
box for fields))
The rest of the functionality I study soon.

I post it on our company sitecore slack as tip for my colleagues with the
github link and a small description of some functions.

I have not searched if it's working on sc 7.2(for a diffent client).


==>
There was one thing not so clear for us....in the instructions on
https://alan-null.github.io/2016/09/sitecore-extensions_v3_0_0

Database Selector

Change your current database in the background by invoking change database
command Alternatively hold CTRL key while executing command to open current
location in different database.
 --
My colleague find by accident that ctrl-space works well and opens the
dialog.
<==

Thanks again and good luck with the development

Met vriendelijke groet \ With regards
Dinand

**Comment by 4Dinand2** [comment]
And to answer your first question, I installed the add-on in firefox and
chrome (3.1)

Met vriendelijke groet \ With regards
Dinand

**Comment by alan-null** [comment]
@4Dinand2 
Thank you for your feedback.
In case you need to know all the details of features here is a link to documentation: 
https://github.com/alan-null/sc_ext/wiki

I am a bit lost now. Do you have any issues using it or I can close the task?

**Comment by 4Dinand2** [comment]
No you can close it, Thanks for the FAST support...

Met vriendelijke groet \ With regards
Dinand

**Comment by alan-null** [comment]
Cool!
Enjoy the extension and submit any ideas for improvements that you have ;)
