### ISSUE TITLE
Scroll to active node for 'Go to Datasource' action

### ISSUE THREAD

**Issue by patelcp** [alan-null/sc_ext#117]
### Steps to Reproduce the Problem
  1. Navigate to a field which has the "Go to Datasource' action
  1. Click 'Go to Datasource' link
  1. Observe how the item selected is updated but the content editor tree remains in the same position
  
### Expected Behavior 
Each time you execute the 'Go to datasource' action which uses Content Editor tree you will be scrolled to the active tree node.

### Actual Behavior
The Content Editor tree does not move

### Specifications
Sitecore version: 8.1 (revision 160519)

**Comment by alan-null** [comment]
Hi @patelcp,

I will install this version later and check. On my current 8.2 Update-6 auto-scroll works fine.
Just in case it will work for me as well there could you tell me what is your browser, chrome/firefox?

**Comment by patelcp** [comment]
Using chrome

**Comment by alan-null** [comment]
Cannot reproduce. Works fine
![htr-chrome](https://user-images.githubusercontent.com/6848691/74768365-bbeb2080-5288-11ea-8f81-40d3e051ad30.gif)
