### ISSUE TITLE
Sitecore 8.2 - Insert options scroll down

### ISSUE THREAD

**Issue by VGBenjamin** [alan-null/sc_ext#120]
### Steps to Reproduce the Problem
  1.  Install a fresh Sitecore 8.2 update 7
  2. Assign a lot of items in the assign options 
  3. Try to insert an item the list is incomplete 
  

### Expected Behavior 
The list should be complete

### Specifications
Sitecore version: 8.2 update 7 (probably also before but the issue doesn't exist in 8.1

Regards,
Benjamin V.

**Comment by alan-null** [comment]
Hey @VGBenjamin 

Could you please paste some screenshot? I am not sure what feature we are talking about.

**Comment by VGBenjamin** [comment]
Without the extension:
![Image without extensiont](https://image.ibb.co/dYWa9o/without_extension.png)

With the extension:
![Image with extension](https://image.ibb.co/kW1Wh8/with_Extension.png)

**Comment by VGBenjamin** [comment]
Here is what the Sitecore support told me about it. This will help you to debugg I think:

It seems like the issue is reproducible on my local machine because of the third-party Google Chrome extension.
One particular extension that was leading to this behavior in my environment is called "Sitecore Extensions".

Please take a look at this screenshot for an example: https://www.screencast.com/t/VknEVOsE
As you can see, the "max-height"  of the element is overwritten by the injected stylesheet.
At the same time, if the extension is disabled, "max-height" is not overwritten and the list is scrollable: https://www.screencast.com/t/UskknaDSkR70

Thus, I kindly ask you to check if the issue is reproducible with Chrome extensions being disabled.
Please note that the extension that affects the behavior might be different in your case.

If disabling extensions doesn't help to resolve the issue, please let us know.
In this case, let us know if the issue is reproducible in any browsers besides Google Chrome.
Additionally, please try checking what overrides the "max-height" of the corresponding "div" element (selected in the 2 screenshots above).

**Comment by alan-null** [comment]
@VGBenjamin thanks a lot, now I know everything.

Unfortunately, there is no way to mitigate this issue with the extension options, so you have to wait for the next update or disable the extension 😞

**Comment by alan-null** [comment]
@VGBenjamin 
Problem solved. Fix will be available in the next release.
![image](https://user-images.githubusercontent.com/6848691/41733760-2fd38ee8-7585-11e8-8011-51bdaaa7aae8.png)
Thank you for reporting.

**Comment by VGBenjamin** [comment]
Great that was really quick thanks a lot!

**Comment by divo-voron** [comment]
Hi.
On Sitecore.NET 9.0.2 (rev. 180604) reproduced the same issue with scroll in insert options

**Extension is enabled:**
![image](https://user-images.githubusercontent.com/6505900/55138122-bb630c00-5143-11e9-8ef4-73e019a649b1.png)

**Extension is disabled:**
![image](https://user-images.githubusercontent.com/6505900/55138151-d0d83600-5143-11e9-90d4-28c1b1e86991.png)

Thanks in advance.
BR,
Dzmitry Voranau

**Comment by alan-null** [comment]
Hey @divo-voron,
Thanks. It was fixed on `master` branch but it is not yet available in the latest public release.
I need to release an update.

**Comment by divo-voron** [comment]
Thank's. I'm looking forward to your next release)
