### ISSUE TITLE
Scrollbar for Popups disabled

### ISSUE THREAD

**Issue by chaelli** [alan-null/sc_ext#121]
### Steps to Reproduce the Problem
  1. Add many insert options
  2. make browser screen small enough, so that not all insert options fit on the screen
  3. try with plugin enabled and disabled
(happens in Chrome and Firefox - haven't tried IE)
  
### Expected Behavior 
There should be a scrollbar

### Actual Behavior
There is no scrollbar when using the Plugin

### Specifications
Sitecore version: Sitecore.NET 8.2 (rev. 170728)

### Screenshot
![image](https://user-images.githubusercontent.com/878151/48469110-2263d200-e7ee-11e8-982b-83690ecb5273.png)
left: with plugin
right: without plugin

### Comments
I found (and marked in the screenshot above) the css that creates the problem. As I couldn't find it within the repository I didn't create a pull request...

**Comment by chaelli** [comment]
Could be related to  #91
but - this seems to have been removed again?

**Comment by alan-null** [comment]
Fixed here: https://github.com/alan-null/sc_ext/issues/120#issuecomment-399173882
