### ISSUE TITLE
Launcher entries are displayed/added when pasting text in Sitecore RTE Paste from Word dialog

### ISSUE THREAD

**Issue by jflheureux** [alan-null/sc_ext#123]
### Steps to Reproduce the Problem
  1. On a Rich Text field of an item, click "Show Editor"
  1. Click the "Paste from Word, strip font" button in the RTE toolbar.
  1. A dialog opens.
     - Actual: The text box to paste text is small on the top-left.
     - Expected: The text box should take the whole space of its container, like when Sitecore Extensions is not active/installed.
  1. Paste any text in the text box.
     - Actual: Sitecore Extensions launcher entries name and descriptions are displayed/added below the text box in its container.
         ![MicrosoftTeams-image](https://user-images.githubusercontent.com/2000200/71988305-abfa0e80-31fd-11ea-86de-c959269c6d46.png)
     - Expected: Sitecore Extensions launcher entries should not be displayed there.

### Specifications
Sitecore version: 9.2 initial release

**Comment by alan-null** [comment]
@jflheureux valid, thank you for reporting
