### ISSUE TITLE
Add ability to copy deep link to currently open item

### ISSUE THREAD

**Issue by aburok** [alan-null/sc_ext#126]
### Expected Behavior 
As a content editor I would like to have an option to copy deep link to current item.

Sitecore version: X.X (revision YYYYY)

**Comment by alan-null** [comment]
@aburok link like this?
`https://sc/sitecore/shell/Applications/Content%20Editor.aspx?sc_bw=1&fo={9C34554C-B669-4978-A85B-0B3328042B07}`
Good idea.

**Comment by aburok** [comment]
yes, exactly like the one you have pasted above. I have some TamperMonkey script written for that. But I would like to have it in the extensions as this is a common functionality.
Also have an option to quickly copy the current Item ID would also be helpfull.
I have also thought about updating the url to reflect current item deep link.

**Comment by aburok** [comment]
I can take a look on how to implement that if you want me to. I noticed that you haven't released any new version since 2017 so is this project dead ?

**Comment by alan-null** [comment]
@aburok it's not dead 😄 
That's my kid!
I planned to release by the end of March but I had to use my resources in a different project
[3.3 release status](https://github.com/alan-null/sc_ext/milestone/6)
I will wrap up and push it ASAP.

**Comment by alan-null** [comment]
Functionality exposed as Launcher command. 
![image](https://user-images.githubusercontent.com/6848691/79364601-e0dad780-7f49-11ea-814f-18220a0fd5a1.png)
In the future, I might melt it somewhere into Content Editor.

**Comment by alan-null** [comment]
@aburok implemented.
Thanks for reporting this idea.

**Comment by aburok** [comment]
Could it be exposed next to the name of database ?

**Comment by alan-null** [comment]
I need to think about it. 
I don't want to put random things there. I was thinking in the past about some "toolbox" for functionalities that don't need to be exposed via Launcher.

**Comment by aburok** [comment]
You are right. But I would suggest that this would be configurable. This way you could choose if you want ot see it or not. And it could be opt-out by default.

**Comment by aburok** [comment]
Could you also add language and database to the deep link feature ?
e.g.
/sitecore/shell/Applications/Content%20Editor.aspx?sc_bw=1&la=en&fo=1B73C413-8CCF-454B-B0BD-33FA60E00777&sc_content=master

**Comment by alan-null** [comment]
@aburok good idea!
