### ISSUE TITLE
Update current content editor url to reflect currently opened item.

### ISSUE THREAD

**Issue by aburok** [alan-null/sc_ext#127]
### Describe the new feature
Update url in the browser to reflect currently opened item.

### How does this help you?
It would allow to easily copy current item url. It would also allow to use back/forward functionality in the browser.

### If we couldn't add this feature, is there a compromise you can think of?

**Comment by alan-null** [comment]
Are you aware of `Back` and `Forward` buttons in **NAVIGATE** section?
![image](https://user-images.githubusercontent.com/6848691/79369455-441c3800-7f51-11ea-8bb5-76605fada24d.png)

I would say they are a compromise.


Updating URL is problematic as it will cause a page to reload.
There is also other problem with this.
You can use Content Editor in two ways 
- direct application window -  URL ➡ `/sitecore/shell/Applications/Content%20Editor.aspx`
- application invoked via Desktop - URL ➡ `sitecore/shell/default.aspx`
You can see URL is different in those cases so it cannot be explicitly used all the time to store CE state.
