### ISSUE TITLE
Display field name in content editor

### ISSUE THREAD

**Issue by skuzniak** [alan-null/sc_ext#13]
As a Sitecore developer I would like to be able to see the actual field name in the content editor so I do not have to search in templates in case Display Name is used.

1. The name of the field is clearly distinguishable form the display name
* The name of the field is displayed before the Display Name
* The name of the field is displayed in square brackets
2. In case the field name is already displayed no additional name is being shown

eg. [THE_FIELD_NAME] Display Name - Help text

**Comment by alan-null** [comment]
@skuzniak Great idea Szymon.
+1 for this feature
