### ISSUE TITLE
Launcher item selection does not work on the Publishing Service dashboard page

### ISSUE THREAD

**Issue by jflheureux** [alan-null/sc_ext#133]
### Steps to Reproduce the Problem
  1. Ensure you have an instance with Publishing Service.
  1. Open the Publishing Service dashboard: http://yourHostName/sitecore/client/Applications/Publishing/Dashboard
  1. Open the launcher with Ctrl+Space.
  1. Using the mouse or Enter keyboard key, try to select an item in the dropdown.

### Expected Behavior
The item is selected, the launcher is hidden, and the action is executed.

### Actual Behavior
Nothing happens.

### Specifications
Sitecore version: 9.3.0 without SXA.

**Comment by alan-null** [comment]
Thanks @jflheureux 
Valid.

**Comment by jflheureux** [comment]
I also reproduced the issue in "Email Experience Manager" on Sitecore 10.0.0. It may be reproduced on 9.3 as well.

1. Open EXM.
1. Open an existing email campaign.
1. On the right side below the "Email campaign info" table, click the "Reports for this email campaign" link.
1. Open the launcher with Ctrl+Space.
1. Using the mouse or Enter keyboard key, try to select an item in the dropdown.

**Comment by alan-null** [comment]
@jflheureux Thanks. It breaks on every "SPEAK app"
List Manager as well. I've got a solution already but until I can access my dev machine it's in my head :)
