### ISSUE TITLE
[Go to field] and Field Inspector don't work anymore

### ISSUE THREAD

**Issue by MidasVE** [alan-null/sc_ext#134]
### Steps to Reproduce the Problem
  1. Go to a field in Sitecore
  1. Click on field title or [Go to field] link next to it

### Expected Behavior
The link goes to the template of the field/the field title shows the name.

### Actual Behavior
It keeps being stuck on '[Loading]'
![image](https://user-images.githubusercontent.com/26002295/94441976-b4d3ab80-01a3-11eb-88ac-321f9002cd62.png)

### Specifications
Sitecore version: 9.0.2
On Microsoft Edge, Google Chrome

**Comment by alan-null** [comment]
@MidasVE does it still fail for you?
Th first usage (after restart) of field name inspector or go to field action button might be slow.

My suspicion is that extension was unable to load information from **dbbrower** before you clicked something else.
First **dbbrowser** load always takes longer, once it's initialized everything should work really fast (you can open chrome dev tools and inspect Network tab)

I cannot reproduce the problem on 9.1. I am constantly using it and don't think that there is something seriously broken there.

If you can reproduce the problem could you check console output in your browser?
That could shed some light on the potential problem that doesn't appear on my side.

**Comment by MidasVE** [comment]
Hi @alan-null 
Thanks for your answer.
This is what I get in the console once I click on the 'go to field' link:
```
: Uncaught SyntaxError: Failed to execute 'querySelector' on 'Document': '[data-sectionid='','','ToggleSection("Blog Overview","0")-0']:not([data-fieldid])' is not a valid selector.
i.cerror @ jsnlog.min.js:1
i.sendLogItemsConsole @ jsnlog.min.js:1
i.sendBatch @ jsnlog.min.js:1
i.log @ jsnlog.min.js:1
n.log @ jsnlog.min.js:1
n.error @ jsnlog.min.js:1
window.onerror @ jsnlog.min.js:1

Application.js:3 Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '[data-sectionid='','','ToggleSection("Blog Overview","0")-0']:not([data-fieldid])' is not a valid selector.
    at getSectionID (chrome-extension://dcbilinfbmohfdhjdekgpgpkcbhmfipl/sc_ext/Application.js:3:15615)
    at XMLHttpRequest.<anonymous> (chrome-extension://dcbilinfbmohfdhjdekgpgpkcbhmfipl/sc_ext/Application.js:3:15796)
getSectionID @ Application.js:3
(anonymous) @ Application.js:3
load (async)
HttpRequest.execute @ Application.js:2
FieldInspectorModule.getItemFields @ Application.js:3
FieldInspectorModule.initFieldIDs @ Application.js:3
FieldInspectorModule.ensureFieldsInitialized @ Application.js:3
spanGoToField.onclick @ Application.js:3

jsnlog.min.js:1 : Uncaught TypeError: Cannot read property 'attributes' of null
i.cerror @ jsnlog.min.js:1
i.sendLogItemsConsole @ jsnlog.min.js:1
i.sendBatch @ jsnlog.min.js:1
i.log @ jsnlog.min.js:1
n.log @ jsnlog.min.js:1
n.error @ jsnlog.min.js:1
window.onerror @ jsnlog.min.js:1

Application.js:3 Uncaught TypeError: Cannot read property 'attributes' of null
    at XMLHttpRequest.<anonymous> (Application.js:3)
(anonymous) @ Application.js:3
load (async)
HttpRequest.execute @ Application.js:2
FieldInspectorModule.getFieldID @ Application.js:3
spanGoToField.onclick @ Application.js:3
```

**Comment by alan-null** [comment]
@MidasVE Thank you. that's really helpful.
I will take a look on it.

**Comment by alan-null** [comment]
@MidasVE I tried to reproduce it but without any luck 😐

Do you have other browser extensions that could influence **sc_ext** functionality (specifically those changing HTML)? 
String "ToggleSection" looks weird to me because normally you will find "toggleSection" (camelCase, first letter lowercased) 
Does it happen for every field? (what's gonna happen if you will inspect Title field of default Home item?)
![image](https://user-images.githubusercontent.com/6848691/95916264-a8a53c00-0da8-11eb-8d0e-8ec725ef2310.png)

If possible could you inspect HTML and show me section `onclick` value?
![image](https://user-images.githubusercontent.com/6848691/95916324-be1a6600-0da8-11eb-930c-cbb448f948da.png)

This is from where the code gets part of the selector from

**Comment by MidasVE** [comment]
Hi @alan-null 

Ok, I've looked at it in Incognito mode to disable all cookies/other extensions and if I look at for example the 'Data' tab of the standard homepage I get this:
![image](https://user-images.githubusercontent.com/26002295/95961506-6bbb6280-0e05-11eb-9e77-2044a976a4e2.png)
As you can see, it somehow also has that 'ToggleSection' instead of 'toggleSection'. I have no other extensions enabled, so I'm not sure why it's capitalizing that first letter there.
This happens on all fields.

Thanks for your help!

**Comment by alan-null** [comment]
@MidasVE Thank you for checking! I was able to reproduce it.

Here is how you can make it work again.
![rendercollapsedsections](https://user-images.githubusercontent.com/6848691/96023712-21f96900-0e53-11eb-9757-8b3181c2a412.gif)

I wasn't aware of this. Actually this seem to be cool a feature (not rendering sections which are closed).
This is temporary workaround, I will see what I can do to support two cases.

**Comment by alan-null** [comment]
Fix will be available in the next version.

**Comment by MidasVE** [comment]
Hi @alan-null 
Thank you! That works 👍
