### ISSUE TITLE
Search fields and sections by name

### ISSUE THREAD

**Issue by skuzniak** [alan-null/sc_ext#14]
As a Sitecore user I want to be able to quickly find a field or section in the Content view in Content Editor so that I don't have to scroll over long list of fields

1. There is a searchbox above the list of fields in the Content Editor
2. When more than 3 characters are entered the list of fields is restricted only to those matching search string
4. The list is updated as the author is typing
5. The list is updated as the author is removing characters
4. If there are less than 3 characters all fields are displayed
3. There is a button to clear the search and display whole list

**Comment by alan-null** [comment]
@skuzniak No more Ctrl+F over whole CE content to find proper section? Great! 
We definitely need this feature.
