### ISSUE TITLE
Feature Request - Show published url for an item

### ISSUE THREAD

**Issue by apphutdev** [alan-null/sc_ext#143]
Would it be possible to introduce a new feature that could open the published url of a item in a new tab?

**Comment by alan-null** [comment]
Hey @apphutdev,

I don't think it's possible. This would require access to Sitecore API.
Considering all the cases (target hostname, virtual folders, other) I don't see a way to do it 😐

**Comment by apphutdev** [comment]
I appreciate the reply thanks
