### ISSUE TITLE
Launcher's key mapping option does not work.

### ISSUE THREAD

**Issue by xirtardauq** [alan-null/sc_ext#144]
I changed the key mapping of "Show Launcher" like the following, but it didn't work. I tried with other keycodes, but the results were the same.

![launcher_key_mappings](https://user-images.githubusercontent.com/52471764/101844221-45107280-3b8f-11eb-9457-fbf9f63bfa9d.png)

### Steps to Reproduce the Problem
  1. Open the options page of the Launcher module.
  1. Set `81` to "Show Launcher".
  1. Press Ctrl + q on Sitecore.

### Expected Behavior
The launcher should be showed.

### Actual Behavior
The launcher does not show up.

### Specifications
Sitecore version: 9.2

**Comment by alan-null** [comment]
Issue exists in included library:
https://github.com/ngx-formly/ngx-formly/issues/729 ("angular-formly": "8.2.1").

Better to hotfix it than upgrade the whole library.

Thanks for reporting and effort trying to solve it! @xirtardauq
