### ISSUE TITLE
Disable auto complete for input field

### ISSUE THREAD

**Issue by HendrikClercx** [alan-null/sc_ext#152]
### Describe the new feature
Possibility to disable auto complete in the input field since this results in unwanted behaviour and overlaps with history of input hits. When pressing the key arrow down, it goes through the auto complete list instead of the history list of this extension.
![image](https://user-images.githubusercontent.com/50102259/225617524-689e96e1-d0c7-4095-b4fe-79c41956ebd3.png)

If possible, introduce a setting to enable/disable this functionality.

Suggestion for fix: 
`<input class="search-field" id="sc-ext-searchBox" **autocomplete="off"**>`

**Comment by alan-null** [comment]
Done. 

Default value: **disabled** (no autocomplete)

![image](https://user-images.githubusercontent.com/6848691/225717332-127aca47-1637-4584-b880-d00149d9cbbe.png)


![image](https://user-images.githubusercontent.com/6848691/225717536-d2fc8954-a162-41e5-b171-a3c0fe37ae89.png)

**Comment by alan-null** [comment]
@HendrikClercx Done. Thanks again for suggestion.

If you don't want to wait for the release you can use "unpacked" version of the extension available here: [sc-ext-3.4.0.zip](https://github.com/alan-null/sc_ext.pre-release/releases/tag/autobuild-2023-03-16-18-28)

**Comment by HendrikClercx** [comment]
Thanks a lot!! Looks perfect and super fast implementation as well :)
