### ISSUE TITLE
Refresh sitecore enhancement

### ISSUE THREAD

**Issue by skuzniak** [alan-null/sc_ext#16]
As an author I want Sitecore to remember my last opened item and restore it on refreshing the page so that I don't have to search for it again.

Given that I have Content Editor opened either in Desktop or standalone
1. When I'm logged out and login again I want the Content Editor to be opened on the same Item that was previously opened
2. When I refresh the page I want the Content Editor to be opened on the same item that was previously opened

**Comment by alan-null** [comment]
@skuzniak 

It was already implemented by @marrrcin
More details here: #2
