### ISSUE TITLE
Some modules disappear when creating new item

### ISSUE THREAD

**Issue by alan-null** [alan-null/sc_ext#22]
### Steps to Reproduce the Problem
1. Open Content Editor
2. Create new item
### Expected Behavior

`Section switches` and `Field search` modules should be visible
### Actual Behavior

After you create new item modules disappear from `EditorTabControls_Content`

**Comment by marrrcin** [comment]
The same behaviour is observed when you restore last opened item.

1. Open Desktop
1. Open Content Editor
1. Ctrl+Space, type _rope_, Enter

**Possible solution**
The modules should attach to item:load event in Content Editor.
