### ISSUE TITLE
Unwanted behavior when clicking x sign in field search input box 

### ISSUE THREAD

**Issue by alan-null** [alan-null/sc_ext#25]
### Steps to Reproduce the Problem
  1. Open Content Editor
  1. Close all sections 
  1. Click `X` in search fields input
  
### Expected Behavior 
Nothing happens 

### Actual Behavior
All sections are expanded

### Specifications
Sitecore version: all

### Additional info
It would be a good idea to use special class for hiding and showing sections back instead of hard coded styles

**Comment by skuzniak** [comment]
This issue has been implemented in a branch field-search-fixes
