### ISSUE TITLE
ShowConfig does not reload page

### ISSUE THREAD

**Issue by marrrcin** [alan-null/sc_ext#27]
### Steps to Reproduce the Problem
  1. Open Desktop
  1. Open Content Editor
  1. Click inside item details section
  1. Ctrl + Space, type _show_, enter

See the screencap:
![showconfigbugscext](https://cloud.githubusercontent.com/assets/6958772/15854104/5af20e24-2ca8-11e6-93a6-286b63062ba0.gif)

  
### Expected Behavior 
Page reloads on /admin/showconfig.aspx page.

### Actual Behavior
Showconfig.aspx seems to display inside the inner iframe.

### Specifications
Sitecore version: 8.1 (revision 160302)

**Comment by alan-null** [comment]
@marrrcin Thank you for the report.
Fixed.

**Comment by marrrcin** [comment]
Great!
