### ISSUE TITLE
Floating database name

### ISSUE THREAD

**Issue by alan-null** [alan-null/sc_ext#47]
### Steps to Reproduce the Problem
  1. Open desktop
  1. See database name
  
### Expected Behavior 
Database name is located in the header like on Sitecore 8.1

### Actual Behavior
Database name located in wrong place
![image](https://cloud.githubusercontent.com/assets/6848691/18204016/b0ddc20e-711a-11e6-81fb-a38310396be2.png)

### Specifications
Sitecore 8.2

**Comment by michaellwest** [comment]
You the man! Any chance it will be fixed by Wednesday? I'll be recording the SPE workshop.

**Comment by alan-null** [comment]
Hello @michaellwest 

My initial plan was to do it later.
I will try do it faster, otherwise you can disable just this module in extension settings or get the latest master branch build from me.

**Comment by alan-null** [comment]
@michaellwest 
Hotfix pushed to the chrome web store so extension supports 8.2 now.
I will postpone 3.0 release little bit.
