### ISSUE TITLE
Interferes with some non-Sitecore sites

### ISSUE THREAD

**Issue by BenGGolden** [alan-null/sc_ext#58]
### Steps to Reproduce the Problem
  1. Have an American Express Card account
  1. Login at https://online.americanexpress.com with the extension enabled
  1. Go to transaction history
  1. Try to sort or filter the transaction list
  
### Expected Behavior 
The transaction list should be sorted or filtered as requested

### Actual Behavior
Nothing happens.  Disabling the extension resolves the issue

### Specifications
Extension version 3.0.0

**Comment by alan-null** [comment]
@BenGGolden Could you provide any console log info?

>Have an American Express Card account 

This is something I cannot get right now.

**Comment by BenGGolden** [comment]
I don't see much difference in the console log when it's enabled rather than disabled.  The icon is grayed out.  I'll try to find some time later to step into the javascript to see if I can find the problem.

**Comment by alan-null** [comment]
Cool, than you for update.
Plain **JS** debugging may be painfull, if you need just let me know and I can provide zip with map files so you could debug in **Type Script** instead.

**Comment by BenGGolden** [comment]
I dug into the javascript and it looks like this is caused by a global variable conflict.  The AmEx site uses the global variable `Status` and so is the extension.  I think either refactoring to limit the use of global variables or simply using a more unique variable name would fix it.

Love the extension, by the way.  Thanks!

**Comment by alan-null** [comment]
@BenGGolden Thank you so much for the detailed information.

All code should live inside `SitecoreExtensions` namespace. 
It turned out that I missed one file where I initialized variables in global context. Problem is already solved.

I am glad to hear you like it.
Thanks to your report and investigation it will be even better now  😃
