### ISSUE TITLE
Expand/Collapse buttons do not appear in Dutch language

### ISSUE THREAD

**Issue by ByteKarim** [alan-null/sc_ext#6]
### Steps to Reproduce the Problem
  1. switch in content editor to 'dutch' language
  2. expand/collapse sections buttons do not appear

  
### Expected Behavior 
Expand/Collapse buttons appear in all languages. Not just English.

### Actual Behavior
Expand/Collapse buttons do not appear in 'Dutch' language.

### Specifications
Sitecore version: Sitecore.NET 8.1 (rev. 160302)

**Comment by ByteKarim** [comment]
Awesome extension by the way ;-)

**Comment by alan-null** [comment]
@ByteKarim Thank you so much for the report and kind words.

Workaround for issues like that is to simply click on the item once again.
![issue-6](https://cloud.githubusercontent.com/assets/6848691/15321130/dcc3ee9c-1c34-11e6-91fa-3eaeef0fdc50.gif)
