### ISSUE TITLE
Different branding for various environments

### ISSUE THREAD

**Issue by alan-null** [alan-null/sc_ext#71]
As a user, I want to be able to define different branding for different environments. 

### Possible modifications:

- [ ] login screen background image
- [ ] desktop background image

**Comment by michaellwest** [comment]
There is currently a feature to change the top bar red when viewing the "web" database. Is there an opportunity to piggyback on that for all environments in all databases?

**Comment by alan-null** [comment]
nope, impossible without additional code right now. This module maps db name to colour only. 
[DatabaseColorModule.ts](https://github.com/alan-null/sc_ext/blob/master/app/sc_ext/modules/databaseColor/DatabaseColorModule.ts#L13)

I am thinking about more generic solution right now (injecting stylesheets), but I am not sure whether it won't be too generic/hard to use. 

My idea is to create a module which lets you define wildcards for URLs and inject different styles for different environments. Additionally there could be predefined styles for most common cases.

Well, there is still design session in my head 😄

**Comment by michaellwest** [comment]
Yes, that is also an idea I had. Often times I want to style the page differently but no way to do that without modifying the Sitecore stylesheets. One example is the menu. Condensing the styles to fit better on smaller screens.

![image](https://cloud.githubusercontent.com/assets/933163/21107254/b1e7b26e-c056-11e6-8eaa-597cdd1ee174.png)

**Comment by alan-null** [comment]
The main goal of this extension is to improve productivity while working with Sitecore CMS. I am not sure if I still see a value in this module/improvement.

Different branding for various environments can be easily achieved with this chrome extension:
https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha

Which covers all scenarios I've planned to implement.
