### ISSUE TITLE
Set Icon

### ISSUE THREAD

**Issue by delawareschidtgroup** [alan-null/sc_ext#72]
### Steps to Reproduce the Problem
  1. Select a template
  2. Use the launcher to set the icon by typing Set Icon 
  
### Expected Behavior 
Be able to set the icon from the launcher

### Actual Behavior
Nothing...  yet ;-)

### Specifications
Sitecore version: 8.1

It could be great if you could add it. Thank you

REgards,

Benjamin Vangansewinkel

**Comment by alan-null** [comment]
Hi @delawareschidtgroup 
Do you mean, to invoke this window
![image](https://cloud.githubusercontent.com/assets/6848691/21133471/3973f6c6-c119-11e6-8a53-84672da1ccc9.png)

via new `Change Icon` command?

**Comment by alan-null** [comment]
Implemented here #74 
![image](https://cloud.githubusercontent.com/assets/6848691/22669463/f942043a-ecc4-11e6-9ceb-f6c410fbc94b.png)

Will be available in version **3.2**
