### ISSUE TITLE
Enhancement: Open in new tab

### ISSUE THREAD

**Issue by WizX20** [alan-null/sc_ext#99]
### Steps to Reproduce the Problem
  1.  Use ctrl+space and open showconfig.aspx

### Expected Behavior 
Open in a new tab in the same browser window: As option in settings.

### Actual Behavior
Always opens in the same tab.

### Specifications
Sitecore version: 8.2

**Comment by alan-null** [comment]
Hi @WizX20,

You can already achieve that.
Just hold `Ctrl` key when you invoke command using Launcher (pressing `Enter` key or double clicking left mouse button)
